<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <PackageId>VmaCS</PackageId>
    <Version>0.2.0</Version>
    <Authors>Aleksey "ViceCop" Volodin</Authors>
    <Description>C# port of AMD Vulkan Memory Allocator.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/vicecop/VmaCS</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>vulkan;vma;memory;allocator;gpu</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <!-- <PackageIcon>icon.png</PackageIcon> -->
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="VmaCS.Tests.Unit" />
    <InternalsVisibleTo Include="VmaCS.Tests.Ported" />
    <InternalsVisibleTo Include="VmaCS.Benchmarks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Silk.NET.Vulkan" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.EXT" />
    <PackageReference Include="Silk.NET.Vulkan.Extensions.KHR" />
    <PackageReference Include="Polyfill" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Memory" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Microsoft.Bcl.HashCode" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.1'">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>